### ISSUE TITLE
Global CSS cannot be imported from within node_modules

### ISSUE THREAD

**Issue by surjithctly** [agneym/playground#15]
Hello,

First of all, thanks for the awesome project. I just installed this playground as per the instructions and when I run on a Next.js Project, I got the following error. Since the error is coming from your plugin, not sure if I can fix this on my side. 

```
./node_modules/@reach/tabs/styles.css
Global CSS cannot be imported from within node_modules.
Read more: https://err.sh/next.js/css-npm
Location: node_modules\@agney\playground\dist\editor.module.js
```

You can see the error on this sandbox as well: https://codesandbox.io/s/affectionate-sanne-5dj0l

**Comment by surjithctly** [comment]
I think, there is a reason why it's blocked by next.js and possible solutions here: https://github.com/vercel/next.js/blob/master/errors/css-npm.md

**Comment by surjithctly** [comment]
Thanks for the fix. 

It works as expected in the codesandbox. but when I add it to my windows project, I again get this error. Any idea why?

![image](https://user-images.githubusercontent.com/1884712/111432552-687d1900-86ba-11eb-94ab-4f86375bf291.png)

**Comment by surjithctly** [comment]
I guess it's because Next.js Server Side renders on Node.js which requires commonJS instead of ESM?

**Comment by agneym** [comment]
I have added a release at `0.6.1`, Can you check if it works with the new version?

**Comment by surjithctly** [comment]
it works like a charm! Thanks a lot. 👍
