### ISSUE TITLE
Feature Request: Option to hide unused Tabs

### ISSUE THREAD

**Issue by surjithctly** [agneym/playground#21]
It would be great if this plugin could provide an option to hide unused tabs. 

For example, if I have a sample code that does not require JS & Console, there is no option to disable it for now. 

Currently, we need to pass empty string such as ` css: `` ` or ` javascript: `` `

**Expected solution:**
When the snippet is not provided, consider it as empty and remove it from the render view. 
Add an option to disable the console tab from the preview. 

Thank you.

**Comment by mikeytown19** [comment]
I came up with a solution for this however I'm not able to push up.

also, I'm not very experienced with open source but I'm trying to get more into it. So sorry if this is the wrong way to go about it.

**Comment by surjithctly** [comment]
For this repo, make changes, then pull request. The author can then approve it.

**Comment by mikeytown19** [comment]
@surjithctly Thanks, the PR is in. I tested locally and everything seems to work also added a new test to make sure.

**Comment by agneym** [comment]
Closed by #33 and released on [0.7.0](https://www.npmjs.com/package/@agney/playground/v/0.7.0)
