### ISSUE TITLE
Uncaught ReferenceError: key_input is not defined  

### ISSUE THREAD

**Issue by mikeytown19** [agneym/playground#34]
After update 7.0 I get this error when typing into the playground.
![Screen Shot 2021-08-16 at 3 07 02 PM](https://user-images.githubusercontent.com/16158800/129629646-a2c6e105-a2e3-4628-9e38-9e3de2f92b7e.png)

I deleted Repo and cloned down the latest version just to make sure and I still get this error.

**Comment by kb1995** [comment]
I just wanted to flag that I just installed it into my app and I got the same error. I downgraded to `^0.6.1` and it worked fine

**Comment by mikeytown19** [comment]
@kb1995 I'm confused about how the Demo example is working? it looks like it's using the most updated version as well.

**Comment by kb1995** [comment]
@mikeytown19 I thought so as well but if you look at the commit history of the README file, it hasn't been updated for 5 months. This means that it's using an older version

**Comment by mikeytown19** [comment]
@kb1995 aww, you're right. I will try working on a fix.

**Comment by mikeytown19** [comment]
Found the bug, just pushed up a fix. 
https://github.com/agneym/playground/pull/35
pretty silly bug actually.

**Comment by agneym** [comment]
Fixed in [v0.7.1](https://www.npmjs.com/package/@agney/playground/v/0.7.1)
