### ISSUE TITLE
Not able to install it in my project

### ISSUE THREAD

**Issue by Ivluengo** [agneym/playground#50]
Hi! I'm having some problems to install it. I'm sending you the error log so you can know what could be. It seems that React 18 might be a problem??

```
npm install @agney/playground
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: test-playground@0.0.0
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"^18.2.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^17.0.1" from @agney/playground@0.8.0
npm ERR! node_modules/@agney/playground
npm ERR!   @agney/playground@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

Thanks a lot!

**Comment by agneym** [comment]
@Ivluengo It seems like I have to get the peer dependencies updated to include React 18. Will get that setup and update here.

**Comment by Ivluengo** [comment]
Thanks a lot @agneym! I didn't have any problem installing it now...but when I use the `<Playground />` component it show some errors in the browser. I tried to do it again in a clean React app and it is happening the same.

*I'm attaching a screenshot*

![image](https://user-images.githubusercontent.com/10440026/197725753-55a0809f-6150-451d-8f4f-6ada5826fca8.png)

Thanks again for your help!

Ivan

**Comment by agneym** [comment]
@Ivluengo It's probably missing the `snippet` prop. Please see the example section

**Comment by Ivluengo** [comment]
> @Ivluengo It's probably missing the `snippet` prop. Please see the example section

My bad....so so sorry. I just tried if it worked without using it correctly. Thanks again!!
