### ISSUE TITLE
Invalid cert - security

### ISSUE THREAD

**Issue by coderbm1** [agneym/playground#61]
Site https://blog.agney.dev/introducing-playground/ is blocked by AV due to invalid cert.

Kind regards

**Comment by agneym** [comment]
Hey! Thanks for opening the issue. I moved my blog to a new URL and seems like the redirect is blocked. 

You should be able to use https://www.agney.dev/blog/introducing-playground to get to the demo. Thanks for opening an issue.

**Comment by coderbm1** [comment]
Hi @agneym thanks a lot! Have a good day
